In [1]:
import numpy as np
import pandas as pd
from math import exp

In [2]:
data = pd.read_csv(r"Social_Network_Ads.csv")
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
count_row = data.shape[0]
count_col = data.shape[1]
print(count_row,count_col)

400 5

In [4]:
X=[]
X = data.Age
X

0      19
1      35
2      26
3      27
4      19
       ..
395    46
396    51
397    50
398    36
399    49
Name: Age, Length: 400, dtype: int64

In [5]:
Y = []
Y = data.Purchased
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [6]:
train_pct_index = int(0.2 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = Y[:train_pct_index], Y[train_pct_index:]

In [7]:
def normalize(X):
    return X - X.mean()


def predict(X, b0, b1):
    predict_array = []
    predict_array = np.array([1 / (1 + exp(-1*b0 + -1*b1*x)) for x in X])
    return predict_array


def logistic_regression(X, Y):

    X = normalize(X)

    b0 = 0
    b1 = 0
    L = 0.001  # learning rate
    epochs = 300

    for epoch in range(epochs):
        y_pred = predict(X, b0, b1)
        D_b0 = -2 * sum((Y - y_pred) * y_pred * (1 - y_pred))  
        D_b1 = -2 * sum(X * (Y - y_pred) * y_pred * (1 - y_pred))  
        b0 = b0 - L * D_b0
        b1 = b1 - L * D_b1
    
    return b0, b1

In [8]:
b0, b1 = logistic_regression(X_train, y_train)

X_test_norm = normalize(X_test)
y_pred = predict(X_test_norm, b0, b1)
print(y_pred)
y_pred = [1 if p >= 0.5 else 0 for p in y_pred]
print(y_pred)

[0.04008571 0.21803044 0.00503934 0.10707028 0.04008571 0.0490387
 0.01164016 0.02665545 0.01764214 0.10707028 0.00766416 0.04008571
 0.01764214 0.03271105 0.03271105 0.10707028 0.10707028 0.02665545
 0.10707028 0.02665545 0.02169574 0.02665545 0.05986658 0.07290201
 0.00408481 0.00621555 0.01764214 0.02169574 0.01764214 0.18420085
 0.21803044 0.15458262 0.18420085 0.15458262 0.34427513 0.25612245
 0.10707028 0.12897388 0.25612245 0.29833052 0.12897388 0.15458262
 0.25612245 0.10707028 0.29833052 0.21803044 0.34427513 0.01764214
 0.04008571 0.01764214 0.0490387  0.07290201 0.04008571 0.00621555
 0.02665545 0.00944719 0.00503934 0.04008571 0.02665545 0.00408481
 0.00408481 0.00331047 0.10707028 0.04008571 0.08850858 0.01164016
 0.02169574 0.29833052 0.03271105 0.00503934 0.01764214 0.29833052
 0.0490387  0.12897388 0.25612245 0.0490387  0.54972042 0.03271105
 0.01764214 0.05986658 0.05986658 0.01433481 0.15458262 0.10707028
 0.07290201 0.00331047 0.00766416 0.10707028 0.03271105 0.03271105
 0.00621555 0.08850858 0.01764214 0.08850858 0.08850858 0.00944719
 0.10707028 0.01433481 0.01164016 0.0490387  0.01764214 0.0490387
 0.05986658 0.07290201 0.07290201 0.0490387  0.00503934 0.07290201
 0.10707028 0.02665545 0.01164016 0.00408481 0.03271105 0.00408481
 0.02665545 0.08850858 0.04008571 0.00503934 0.01764214 0.10707028
 0.10707028 0.69686683 0.21803044 0.29833052 0.93883502 0.60120811
 0.89072655 0.81234243 0.25612245 0.54972042 0.65055094 0.81234243
 0.94988523 0.10707028 0.60120811 0.9590262  0.69686683 0.25612245
 0.54972042 0.94988523 0.29833052 0.10707028 0.15458262 0.9590262
 0.10707028 0.15458262 0.12897388 0.90963154 0.25612245 0.34427513
 0.10707028 0.21803044 0.25612245 0.69686683 0.18420085 0.54972042
 0.25612245 0.15458262 0.54972042 0.84240911 0.34427513 0.18420085
 0.73950212 0.90963154 0.29833052 0.77805071 0.10707028 0.92553927
 0.29833052 0.10707028 0.44463311 0.15458262 0.65055094 0.15458262
 0.73950212 0.81234243 0.29833052 0.25612245 0.93883502 0.49714524
 0.10707028 0.12897388 0.89072655 0.10707028 0.65055094 0.34427513
 0.25612245 0.15458262 0.60120811 0.25612245 0.3933291  0.94988523
 0.9590262  0.21803044 0.92553927 0.92553927 0.18420085 0.69686683
 0.81234243 0.73950212 0.94988523 0.10707028 0.15458262 0.81234243
 0.65055094 0.15458262 0.15458262 0.65055094 0.29833052 0.15458262
 0.21803044 0.69686683 0.89072655 0.15458262 0.10707028 0.12897388
 0.34427513 0.3933291  0.49714524 0.54972042 0.93883502 0.65055094
 0.15458262 0.15458262 0.25612245 0.34427513 0.77805071 0.60120811
 0.12897388 0.18420085 0.34427513 0.21803044 0.18420085 0.69686683
 0.21803044 0.21803044 0.86843866 0.10707028 0.49714524 0.12897388
 0.81234243 0.84240911 0.29833052 0.65055094 0.65055094 0.29833052
 0.29833052 0.34427513 0.12897388 0.60120811 0.18420085 0.65055094
 0.34427513 0.25612245 0.92553927 0.12897388 0.93883502 0.10707028
 0.18420085 0.21803044 0.84240911 0.10707028 0.18420085 0.60120811
 0.60120811 0.29833052 0.84240911 0.86843866 0.21803044 0.18420085
 0.18420085 0.15458262 0.34427513 0.15458262 0.12897388 0.9590262
 0.86843866 0.29833052 0.25612245 0.34427513 0.3933291  0.84240911
 0.60120811 0.34427513 0.34427513 0.94988523 0.93883502 0.54972042
 0.18420085 0.86843866 0.9590262  0.9590262  0.21803044 0.94988523
 0.15458262 0.54972042 0.54972042 0.34427513 0.29833052 0.93883502
 0.34427513 0.65055094 0.44463311 0.69686683 0.92553927 0.90963154
 0.69686683 0.21803044 0.60120811 0.65055094 0.65055094 0.60120811
 0.49714524 0.9590262  0.21803044 0.54972042 0.77805071 0.73950212
 0.12897388 0.69686683]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1]

In [9]:
accuracy = 0
for i in range(len(y_pred)):
    if y_test.iloc[i] == y_pred[i]:
        accuracy += 1
print(accuracy / float(len(y_test)) * 100.0)

80.9375